server:
  port: 8101
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuyj1111/config-info.git
          searchPaths: '{application}'                          #搜索目录
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
